// Competitor model data for comparison tool
// This data can be synced from CarDekho/CarWale or entered manually

export interface CompetitorSpecs {
  engine: string
  power: string
  torque: string
  transmission: string
  fuelType: string
  mileage: string
  length: string
  width: string
  height: string
  wheelbase: string
  bootSpace: string
  groundClearance: string
  fuelTank: string
  seatingCapacity: string
  airbags: string
  warranty: string
}

export interface CompetitorModelData {
  id: string
  name: string
  brand: string
  segment: string
  priceRange: string
  imageUrl: string
  sourceUrl?: string
  competesWith: string[] // Kia model slugs
  specs: CompetitorSpecs
}

// Competitor data organized by segment
export const COMPETITOR_MODELS: CompetitorModelData[] = [
  // Compact SUV segment (Seltos competitors)
  {
    id: 'hyundai-creta',
    name: 'Hyundai Creta',
    brand: 'Hyundai',
    segment: 'compact_suv',
    priceRange: '₹11.0 - 20.2 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=Hyundai+Creta',
    sourceUrl: 'https://www.cardekho.com/hyundai/creta',
    competesWith: ['seltos'],
    specs: {
      engine: '1.5L Petrol / 1.5L Diesel / 1.5L Turbo',
      power: '115 - 160 bhp',
      torque: '144 - 253 Nm',
      transmission: '6MT / IVT / 7DCT',
      fuelType: 'Petrol / Diesel',
      mileage: '16.8 - 21.8 km/l',
      length: '4,330 mm',
      width: '1,790 mm',
      height: '1,635 mm',
      wheelbase: '2,610 mm',
      bootSpace: '433 L',
      groundClearance: '190 mm',
      fuelTank: '50 L',
      seatingCapacity: '5',
      airbags: '6',
      warranty: '3 Years / Unlimited km',
    },
  },
  {
    id: 'tata-nexon',
    name: 'Tata Nexon',
    brand: 'Tata',
    segment: 'compact_suv',
    priceRange: '₹8.1 - 15.5 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=Tata+Nexon',
    sourceUrl: 'https://www.cardekho.com/tata/nexon',
    competesWith: ['seltos', 'sonet'],
    specs: {
      engine: '1.2L Turbo Petrol / 1.5L Diesel',
      power: '120 - 170 bhp',
      torque: '170 - 260 Nm',
      transmission: '6MT / 6AMT / 7DCA',
      fuelType: 'Petrol / Diesel',
      mileage: '17.4 - 24.1 km/l',
      length: '3,993 mm',
      width: '1,811 mm',
      height: '1,606 mm',
      wheelbase: '2,498 mm',
      bootSpace: '382 L',
      groundClearance: '208 mm',
      fuelTank: '44 L',
      seatingCapacity: '5',
      airbags: '6',
      warranty: '3 Years / 1 Lakh km',
    },
  },
  {
    id: 'honda-elevate',
    name: 'Honda Elevate',
    brand: 'Honda',
    segment: 'compact_suv',
    priceRange: '₹11.7 - 16.0 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=Honda+Elevate',
    sourceUrl: 'https://www.cardekho.com/honda/elevate',
    competesWith: ['seltos'],
    specs: {
      engine: '1.5L i-VTEC Petrol',
      power: '121 bhp',
      torque: '145 Nm',
      transmission: '6MT / CVT',
      fuelType: 'Petrol',
      mileage: '15.3 - 16.9 km/l',
      length: '4,312 mm',
      width: '1,790 mm',
      height: '1,650 mm',
      wheelbase: '2,650 mm',
      bootSpace: '458 L',
      groundClearance: '220 mm',
      fuelTank: '40 L',
      seatingCapacity: '5',
      airbags: '6',
      warranty: '3 Years / Unlimited km',
    },
  },
  {
    id: 'mg-astor',
    name: 'MG Astor',
    brand: 'MG',
    segment: 'compact_suv',
    priceRange: '₹10.0 - 17.3 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=MG+Astor',
    sourceUrl: 'https://www.cardekho.com/mg/astor',
    competesWith: ['seltos'],
    specs: {
      engine: '1.5L Petrol / 1.3L Turbo',
      power: '110 - 140 bhp',
      torque: '144 - 220 Nm',
      transmission: '5MT / CVT / 6AT',
      fuelType: 'Petrol',
      mileage: '14.9 - 17.2 km/l',
      length: '4,323 mm',
      width: '1,809 mm',
      height: '1,650 mm',
      wheelbase: '2,585 mm',
      bootSpace: '359 L',
      groundClearance: '211 mm',
      fuelTank: '50 L',
      seatingCapacity: '5',
      airbags: '6',
      warranty: '5 Years / Unlimited km',
    },
  },

  // Subcompact SUV segment (Sonet competitors)
  {
    id: 'hyundai-venue',
    name: 'Hyundai Venue',
    brand: 'Hyundai',
    segment: 'subcompact_suv',
    priceRange: '₹7.9 - 13.5 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=Hyundai+Venue',
    sourceUrl: 'https://www.cardekho.com/hyundai/venue',
    competesWith: ['sonet'],
    specs: {
      engine: '1.2L Petrol / 1.0L Turbo / 1.5L Diesel',
      power: '83 - 120 bhp',
      torque: '114 - 240 Nm',
      transmission: '5MT / 6iMT / 7DCT / 6MT',
      fuelType: 'Petrol / Diesel',
      mileage: '17.5 - 23.4 km/l',
      length: '3,995 mm',
      width: '1,770 mm',
      height: '1,617 mm',
      wheelbase: '2,500 mm',
      bootSpace: '350 L',
      groundClearance: '195 mm',
      fuelTank: '45 L',
      seatingCapacity: '5',
      airbags: '6',
      warranty: '3 Years / Unlimited km',
    },
  },
  {
    id: 'tata-punch',
    name: 'Tata Punch',
    brand: 'Tata',
    segment: 'subcompact_suv',
    priceRange: '₹6.1 - 10.2 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=Tata+Punch',
    sourceUrl: 'https://www.cardekho.com/tata/punch',
    competesWith: ['sonet'],
    specs: {
      engine: '1.2L Petrol',
      power: '86 bhp',
      torque: '113 Nm',
      transmission: '5MT / 5AMT',
      fuelType: 'Petrol',
      mileage: '18.8 - 20.1 km/l',
      length: '3,827 mm',
      width: '1,742 mm',
      height: '1,615 mm',
      wheelbase: '2,445 mm',
      bootSpace: '366 L',
      groundClearance: '187 mm',
      fuelTank: '37 L',
      seatingCapacity: '5',
      airbags: '6',
      warranty: '3 Years / 1 Lakh km',
    },
  },
  {
    id: 'mahindra-xuv3xo',
    name: 'Mahindra XUV 3XO',
    brand: 'Mahindra',
    segment: 'subcompact_suv',
    priceRange: '₹7.5 - 15.5 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=Mahindra+XUV+3XO',
    sourceUrl: 'https://www.cardekho.com/mahindra/xuv-3xo',
    competesWith: ['sonet'],
    specs: {
      engine: '1.2L Petrol / 1.2L Turbo / 1.5L Diesel',
      power: '110 - 130 bhp',
      torque: '200 - 300 Nm',
      transmission: '6MT / 6AT',
      fuelType: 'Petrol / Diesel',
      mileage: '17.0 - 20.6 km/l',
      length: '3,990 mm',
      width: '1,821 mm',
      height: '1,647 mm',
      wheelbase: '2,600 mm',
      bootSpace: '364 L',
      groundClearance: '195 mm',
      fuelTank: '42 L',
      seatingCapacity: '5',
      airbags: '6',
      warranty: '3 Years / 1 Lakh km',
    },
  },
  {
    id: 'maruti-brezza',
    name: 'Maruti Brezza',
    brand: 'Maruti Suzuki',
    segment: 'subcompact_suv',
    priceRange: '₹8.3 - 14.1 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=Maruti+Brezza',
    sourceUrl: 'https://www.cardekho.com/maruti-suzuki/brezza',
    competesWith: ['sonet'],
    specs: {
      engine: '1.5L Petrol / 1.5L Mild Hybrid',
      power: '103 bhp',
      torque: '137 Nm',
      transmission: '5MT / 6AT',
      fuelType: 'Petrol',
      mileage: '17.4 - 20.2 km/l',
      length: '3,995 mm',
      width: '1,790 mm',
      height: '1,685 mm',
      wheelbase: '2,500 mm',
      bootSpace: '328 L',
      groundClearance: '198 mm',
      fuelTank: '48 L',
      seatingCapacity: '5',
      airbags: '6',
      warranty: '3 Years / 1 Lakh km',
    },
  },

  // MPV segment (Carens competitors)
  {
    id: 'hyundai-alcazar',
    name: 'Hyundai Alcazar',
    brand: 'Hyundai',
    segment: 'mpv',
    priceRange: '₹17.0 - 21.6 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=Hyundai+Alcazar',
    sourceUrl: 'https://www.cardekho.com/hyundai/alcazar',
    competesWith: ['carens'],
    specs: {
      engine: '1.5L Turbo Petrol / 1.5L Diesel',
      power: '160 - 160 bhp',
      torque: '253 - 250 Nm',
      transmission: '6MT / 6AT / 7DCT',
      fuelType: 'Petrol / Diesel',
      mileage: '14.5 - 20.4 km/l',
      length: '4,500 mm',
      width: '1,790 mm',
      height: '1,675 mm',
      wheelbase: '2,760 mm',
      bootSpace: '180 L (all rows up)',
      groundClearance: '200 mm',
      fuelTank: '50 L',
      seatingCapacity: '6/7',
      airbags: '6',
      warranty: '3 Years / Unlimited km',
    },
  },
  {
    id: 'mahindra-xuv700',
    name: 'Mahindra XUV700',
    brand: 'Mahindra',
    segment: 'mpv',
    priceRange: '₹14.0 - 26.0 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=Mahindra+XUV700',
    sourceUrl: 'https://www.cardekho.com/mahindra/xuv700',
    competesWith: ['carens'],
    specs: {
      engine: '2.0L Petrol / 2.2L Diesel',
      power: '200 - 185 bhp',
      torque: '380 - 450 Nm',
      transmission: '6MT / 6AT',
      fuelType: 'Petrol / Diesel',
      mileage: '13.0 - 16.0 km/l',
      length: '4,695 mm',
      width: '1,890 mm',
      height: '1,755 mm',
      wheelbase: '2,750 mm',
      bootSpace: '239 L (all rows up)',
      groundClearance: '200 mm',
      fuelTank: '60 L',
      seatingCapacity: '5/7',
      airbags: '7',
      warranty: '3 Years / 1 Lakh km',
    },
  },
  {
    id: 'toyota-innova-hycross',
    name: 'Toyota Innova Hycross',
    brand: 'Toyota',
    segment: 'mpv',
    priceRange: '₹19.8 - 30.5 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=Toyota+Innova+Hycross',
    sourceUrl: 'https://www.cardekho.com/toyota/innova-hycross',
    competesWith: ['carens', 'carnival'],
    specs: {
      engine: '2.0L Petrol / 2.0L Hybrid',
      power: '174 - 186 bhp',
      torque: '188 - 206 Nm',
      transmission: 'CVT',
      fuelType: 'Petrol / Hybrid',
      mileage: '16.2 - 21.1 km/l',
      length: '4,755 mm',
      width: '1,850 mm',
      height: '1,795 mm',
      wheelbase: '2,850 mm',
      bootSpace: '239 L (all rows up)',
      groundClearance: '185 mm',
      fuelTank: '52 L',
      seatingCapacity: '7/8',
      airbags: '6',
      warranty: '3 Years / 1 Lakh km',
    },
  },

  // EV segment (EV6/EV9 competitors)
  {
    id: 'hyundai-ioniq5',
    name: 'Hyundai Ioniq 5',
    brand: 'Hyundai',
    segment: 'ev',
    priceRange: '₹46.0 - 47.0 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=Hyundai+Ioniq+5',
    sourceUrl: 'https://www.cardekho.com/hyundai/ioniq-5',
    competesWith: ['ev6'],
    specs: {
      engine: '72.6 kWh Battery',
      power: '217 bhp (RWD)',
      torque: '350 Nm',
      transmission: 'Single Speed',
      fuelType: 'Electric',
      mileage: '631 km (ARAI)',
      length: '4,635 mm',
      width: '1,890 mm',
      height: '1,605 mm',
      wheelbase: '3,000 mm',
      bootSpace: '527 L',
      groundClearance: '160 mm',
      fuelTank: 'N/A',
      seatingCapacity: '5',
      airbags: '6',
      warranty: '3 Years / Unlimited km',
    },
  },
  {
    id: 'tata-nexon-ev',
    name: 'Tata Nexon EV',
    brand: 'Tata',
    segment: 'ev',
    priceRange: '₹14.5 - 19.8 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=Tata+Nexon+EV',
    sourceUrl: 'https://www.cardekho.com/tata/nexon-ev',
    competesWith: ['ev6'],
    specs: {
      engine: '40.5 kWh Battery',
      power: '143 bhp',
      torque: '215 Nm',
      transmission: 'Single Speed',
      fuelType: 'Electric',
      mileage: '465 km (ARAI)',
      length: '3,993 mm',
      width: '1,811 mm',
      height: '1,616 mm',
      wheelbase: '2,498 mm',
      bootSpace: '350 L',
      groundClearance: '205 mm',
      fuelTank: 'N/A',
      seatingCapacity: '5',
      airbags: '6',
      warranty: '3 Years / 1.25 Lakh km',
    },
  },
  {
    id: 'mg-zs-ev',
    name: 'MG ZS EV',
    brand: 'MG',
    segment: 'ev',
    priceRange: '₹18.9 - 25.2 Lakh',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/ffffff?text=MG+ZS+EV',
    sourceUrl: 'https://www.cardekho.com/mg/zs-ev',
    competesWith: ['ev6'],
    specs: {
      engine: '50.3 kWh Battery',
      power: '177 bhp',
      torque: '280 Nm',
      transmission: 'Single Speed',
      fuelType: 'Electric',
      mileage: '461 km (ARAI)',
      length: '4,314 mm',
      width: '1,809 mm',
      height: '1,644 mm',
      wheelbase: '2,580 mm',
      bootSpace: '448 L',
      groundClearance: '177 mm',
      fuelTank: 'N/A',
      seatingCapacity: '5',
      airbags: '6',
      warranty: '5 Years / Unlimited km',
    },
  },
]

// Get competitors for a Kia model
export function getCompetitorsForModel(modelSlug: string): CompetitorModelData[] {
  return COMPETITOR_MODELS.filter((c) => c.competesWith.includes(modelSlug))
}

// Get all competitors in a segment
export function getCompetitorsBySegment(segment: string): CompetitorModelData[] {
  return COMPETITOR_MODELS.filter((c) => c.segment === segment)
}

// Get competitor by ID
export function getCompetitorById(id: string): CompetitorModelData | undefined {
  return COMPETITOR_MODELS.find((c) => c.id === id)
}

// Kia model specs for comparison (mapped to same format as competitors)
export const KIA_MODEL_SPECS: Record<string, CompetitorSpecs> = {
  seltos: {
    engine: '1.5L Petrol / 1.5L Diesel / 1.4L Turbo',
    power: '115 - 140 bhp',
    torque: '144 - 242 Nm',
    transmission: '6MT / IVT / 7DCT / 6AT',
    fuelType: 'Petrol / Diesel',
    mileage: '16.5 - 21.0 km/l',
    length: '4,365 mm',
    width: '1,800 mm',
    height: '1,645 mm',
    wheelbase: '2,610 mm',
    bootSpace: '433 L',
    groundClearance: '190 mm',
    fuelTank: '50 L',
    seatingCapacity: '5',
    airbags: '6',
    warranty: '7 Years / Unlimited km',
  },
  sonet: {
    engine: '1.2L Petrol / 1.5L Diesel / 1.0L Turbo',
    power: '83 - 120 bhp',
    torque: '115 - 240 Nm',
    transmission: '5MT / 6MT / 6iMT / 7DCT / 6AT',
    fuelType: 'Petrol / Diesel',
    mileage: '18.3 - 24.1 km/l',
    length: '3,995 mm',
    width: '1,790 mm',
    height: '1,647 mm',
    wheelbase: '2,500 mm',
    bootSpace: '392 L',
    groundClearance: '205 mm',
    fuelTank: '45 L',
    seatingCapacity: '5',
    airbags: '6',
    warranty: '7 Years / Unlimited km',
  },
  carens: {
    engine: '1.5L Petrol / 1.5L Diesel / 1.4L Turbo',
    power: '115 - 140 bhp',
    torque: '144 - 242 Nm',
    transmission: '6MT / 7DCT / 6AT',
    fuelType: 'Petrol / Diesel',
    mileage: '14.0 - 21.3 km/l',
    length: '4,540 mm',
    width: '1,800 mm',
    height: '1,708 mm',
    wheelbase: '2,780 mm',
    bootSpace: '216 L (all rows up)',
    groundClearance: '195 mm',
    fuelTank: '45 L',
    seatingCapacity: '6/7',
    airbags: '6',
    warranty: '7 Years / Unlimited km',
  },
  carnival: {
    engine: '2.2L Diesel',
    power: '200 bhp',
    torque: '440 Nm',
    transmission: '8AT',
    fuelType: 'Diesel',
    mileage: '14.1 km/l',
    length: '5,155 mm',
    width: '1,995 mm',
    height: '1,740 mm',
    wheelbase: '3,090 mm',
    bootSpace: '627 L (third row up)',
    groundClearance: '175 mm',
    fuelTank: '72 L',
    seatingCapacity: '7/8/9',
    airbags: '6',
    warranty: '7 Years / Unlimited km',
  },
  ev6: {
    engine: '77.4 kWh Battery',
    power: '229 - 325 bhp',
    torque: '350 - 605 Nm',
    transmission: 'Single Speed',
    fuelType: 'Electric',
    mileage: '528 km (ARAI)',
    length: '4,680 mm',
    width: '1,880 mm',
    height: '1,550 mm',
    wheelbase: '2,900 mm',
    bootSpace: '480 L',
    groundClearance: '160 mm',
    fuelTank: 'N/A',
    seatingCapacity: '5',
    airbags: '6',
    warranty: '7 Years / Unlimited km',
  },
  ev9: {
    engine: '99.8 kWh Battery',
    power: '204 - 385 bhp',
    torque: '350 - 700 Nm',
    transmission: 'Single Speed',
    fuelType: 'Electric',
    mileage: '561 km (ARAI)',
    length: '5,010 mm',
    width: '1,980 mm',
    height: '1,755 mm',
    wheelbase: '3,100 mm',
    bootSpace: '828 L',
    groundClearance: '199 mm',
    fuelTank: 'N/A',
    seatingCapacity: '6/7',
    airbags: '7+',
    warranty: '7 Years / Unlimited km',
  },
  syros: {
    engine: '1.0L Turbo Petrol / 1.5L Diesel',
    power: '120 - 116 bhp',
    torque: '172 - 250 Nm',
    transmission: '6MT / 7DCT / 6AT',
    fuelType: 'Petrol / Diesel',
    mileage: '18.0 - 20.0 km/l',
    length: '4,100 mm',
    width: '1,800 mm',
    height: '1,665 mm',
    wheelbase: '2,580 mm',
    bootSpace: '465 L',
    groundClearance: '190 mm',
    fuelTank: '45 L',
    seatingCapacity: '5',
    airbags: '6',
    warranty: '7 Years / Unlimited km',
  },
}

// Kia advantage highlights (for comparison display)
export const KIA_ADVANTAGES = [
  {
    title: 'Industry-Leading Warranty',
    description: '7 Years / Unlimited km warranty - best in class',
  },
  {
    title: 'Premium Features',
    description: 'Connected car tech, panoramic sunroof, ventilated seats',
  },
  {
    title: 'Award-Winning Design',
    description: 'Global design language with premium fit & finish',
  },
  {
    title: 'After-Sales Excellence',
    description: '280+ touchpoints across India, transparent pricing',
  },
]
